In [3]:
import pandas as pd
import numpy as np

In [4]:
info = {
    "Name": ["Nithish", "rahul", "sai"],
    "CGPA": [9.5, 7.5, 8.5]
}

df = pd.DataFrame(info)
print(df)

      Name  CGPA
0  Nithish   9.5
1    rahul   7.5
2      sai   8.5

In [5]:
df

      Name  CGPA
0  Nithish   9.5
1    rahul   7.5
2      sai   8.5

In [7]:

# Series in pandas
s = pd.Series([23, 24, 25, 26])

print(s)
print(type(s))

# Indexing
print(s[0])    # 23
print(s[2])    # 25

# Display all index labels
print(s.index)

# Custom Indexing
s2 = pd.Series(
    [23, 24, 25, 26],
    index=["Adam", "Eve", "Charlie", "Bob"]
)

print(s2["Eve"])    # 24
print(s2["Bob"])    # 26

# Vectorized Operations
s1 = pd.Series([1, 2, 3])
s2 = pd.Series([4, 5, 6])

print(s1 + s2)
# Output:
# 0    5
# 1    7
# 2    9

# Mutable Values but Immutable Size
s = pd.Series([1, 2, 3, 4, 5])

# Changing an existing value
s[0] = 100

print(s)

# Drop an element
changed_s = s.drop(1)

print(changed_s)

# Original Series remains unchanged
print(s)

0    23
1    24
2    25
3    26
dtype: int64
<class 'pandas.core.series.Series'>
23
25
RangeIndex(start=0, stop=4, step=1)
24
26
0    5
1    7
2    9
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64
0    100
2      3
3      4
4      5
dtype: int64
0    100
1      2
2      3
3      4
4      5
dtype: int64

In [8]:
# DataFrame in pandas - using dictionary
info = {
    "Name" : ["Adam", "Eve", "Bob"],
    "Marks" : [78, 99, 85],
    "Grade" : ['B', 'O', 'A']
}

df = pd.DataFrame(info)

print(df)
print(type(df))

print(df.index)        # row labels
print(df.columns)      # column labels

# DataFrom using Numpy array
np_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
df = pd.DataFrame(np_arr, columns=["Col1", "Col2", "Col3"])
print(df)

# DataFrom using Lists
l = [["Adam", 96], ["Eve", 75], ["Bob", 82], ["Charlie", 92]]
df = pd.DataFrame(l, columns=["Name", "Marks"])
print(df)

   Name  Marks Grade
0  Adam     78     B
1   Eve     99     O
2   Bob     85     A
<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Marks', 'Grade'], dtype='object')
   Col1  Col2  Col3
0     1     2     3
1     4     5     6
2     7     8     9
      Name  Marks
0     Adam     96
1      Eve     75
2      Bob     82
3  Charlie     92

In [14]:
# pandas with csv files
data = pd.read_csv("employee_data.csv")
print(data, type(data))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [18]:
 # DataFrame Methods
df = pd.read_csv("employee_data.csv")

print(df.head())
print(df.tail())
print(df.sample())
print(df.info())
print(df.shape)
print(df.describe())
print(df.columns)
print(df.nunique())

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
   ID    Name  Age Department  Salary
5   6   Frank   29    Finance   50000
6   7   Grace   41         HR   82000
7   8  Hannah   26  Marketing   47000
8   9     Ian   35         IT   75000
9  10   Julia   30    Finance   60000
   ID Name  Age Department  Salary
4   5  Eva   38         IT   65000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     object
 2   Age         10 non-null     int64
 3   Department  10 non-null     object
 4   Salary      10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes
None
(10, 5)
             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000
Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='object')
ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [21]:
#kaggle Global Air Quality Data(15 Days Hourly, 50 Cities)
df = pd.read_csv("globalAirQuality.csv")
df

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17995,2025-11-19 13:25:17.554219,CH,Zurich,47.377,8.542,27.899,74.179,41.474,6.677,50.869,1.028,103,7.079,52.443,7.452
17996,2025-11-19 14:25:17.554219,CH,Zurich,47.377,8.542,2.950,47.988,42.235,2.821,35.551,0.644,105,28.734,85.678,4.496
17997,2025-11-19 15:25:17.554219,CH,Zurich,47.377,8.542,61.347,72.908,46.976,5.763,66.492,0.947,122,21.951,72.311,9.660
17998,2025-11-19 16:25:17.554219,CH,Zurich,47.377,8.542,40.722,95.152,32.957,5.524,53.193,0.868,95,24.042,31.880,2.642
17999,2025-11-19 17:25:17.554219,CH,Zurich,47.377,8.542,25.830,30.411,35.317,4.336,66.246,0.848,88,8.529,59.104,4.403

In [26]:
print(df.head())
print(df.tail())
print(df.sample())
print(df.info())
print(df.shape)
print(df.describe())

                    timestamp country      city  latitude  longitude    pm25  \
0  2025-11-04 18:25:17.554219      US  New York    40.713    -74.006  50.295
1  2025-11-04 19:25:17.554219      US  New York    40.713    -74.006  32.083
2  2025-11-04 20:25:17.554219      US  New York    40.713    -74.006  42.250
3  2025-11-04 21:25:17.554219      US  New York    40.713    -74.006  30.403
4  2025-11-04 22:25:17.554219      US  New York    40.713    -74.006  21.083

      pm10     no2    so2      o3     co  aqi  temperature  humidity  \
0  108.938  27.998  6.539  52.568  1.096  108       18.504    70.168
1   63.043  36.120  4.021  43.536  1.075   90        5.838    80.088
2   82.553  26.935  9.538  23.320  0.977   84       31.833    62.783
3   79.951  63.536  7.609  31.369  0.230  158       23.140    89.153
4   66.423  38.997  6.919  45.615  1.085   97       13.632    76.499

   wind_speed
0       3.725
1       8.969
2       9.650
3       8.956
4       4.017
                        timestamp country    city  latitude  longitude  \
17995  2025-11-19 13:25:17.554219      CH  Zurich    47.377      8.542
17996  2025-11-19 14:25:17.554219      CH  Zurich    47.377      8.542
17997  2025-11-19 15:25:17.554219      CH  Zurich    47.377      8.542
17998  2025-11-19 16:25:17.554219      CH  Zurich    47.377      8.542
17999  2025-11-19 17:25:17.554219      CH  Zurich    47.377      8.542

         pm25    pm10     no2    so2      o3     co  aqi  temperature  \
17995  27.899  74.179  41.474  6.677  50.869  1.028  103        7.079
17996   2.950  47.988  42.235  2.821  35.551  0.644  105       28.734
17997  61.347  72.908  46.976  5.763  66.492  0.947  122       21.951
17998  40.722  95.152  32.957  5.524  53.193  0.868   95       24.042
17999  25.830  30.411  35.317  4.336  66.246  0.848   88        8.529

       humidity  wind_speed
17995    52.443       7.452
17996    85.678       4.496
17997    72.311       9.660
17998    31.880       2.642
17999    59.104       4.403
                        timestamp country      city  latitude  longitude  \
12732  2025-11-10 06:25:17.554219      NZ  Auckland   -36.848    174.763

         pm25    pm10     no2    so2     o3    co  aqi  temperature  humidity  \
12732  69.252  70.246  50.253  9.709  53.67  0.74  138        33.25    57.438

       wind_speed
12732       6.396
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18000 entries, 0 to 17999
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    18000 non-null  object
 1   country      18000 non-null  object
 2   city         18000 non-null  object
 3   latitude     18000 non-null  float64
 4   longitude    18000 non-null  float64
 5   pm25         18000 non-null  float64
 6   pm10         18000 non-null  float64
 7   no2          18000 non-null  float64
 8   so2          18000 non-null  float64
 9   o3           18000 non-null  float64
 10  co           18000 non-null  float64
 11  aqi          18000 non-null  int64
 12  temperature  18000 non-null  float64
 13  humidity     18000 non-null  float64
 14  wind_speed   18000 non-null  float64
dtypes: float64(11), int64(1), object(3)
memory usage: 2.1+ MB
None
(18000, 15)
           latitude     longitude          pm25          pm10           no2  \
count  18000.000000  18000.000000  18000.000000  18000.000000  18000.000000
mean      23.065980     37.655560     40.369131     70.152228     32.055176
std       26.156536     78.600701     17.647450     24.999440     13.820680
min      -37.814000   -123.121000      0.025000      0.061000      0.013000
25%       12.972000      2.352000     27.904500     53.125500     22.362500
50%       29.232000     42.146000     40.286500     69.961000     32.019500
75%       41.008000    103.820000     52.436250     87.256500     41.364250
max       60.170000    174.763000    115.683000    161.810000     90.019000

                so2            o3            co           aqi   temperature  \
count  18000.000000  18000.000000  18000.000000  18000.000000  18000.000000
mean       6.035508     48.065100      0.800595    104.645556     21.510251
std        2.454790     14.950849      0.250254     25.616070      9.509444
min        0.003000      0.114000      0.000000     16.000000      5.000000
25%        4.360750     38.028500      0.633000     87.000000     13.357750
50%        6.026000     48.142000      0.800500    103.000000     21.455500
75%        7.715250     58.258500      0.969000    121.000000     29.688250
max       16.559000    103.016000      1.832000    231.000000     37.998000

           humidity    wind_speed
count  18000.000000  18000.000000
mean      57.714351      5.283910
std       18.844908      2.741712
min       25.002000      0.500000
25%       41.320000      2.937000
50%       57.847000      5.297000
75%       74.234750      7.662000
max       89.997000      9.999000

In [29]:
# Selecting Data

# Select columns
df["country"]
df[["city", "aqi"]]

           city  aqi
0      New York  108
1      New York   90
2      New York   84
3      New York  158
4      New York   97
...         ...  ...
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122
17998    Zurich   95
17999    Zurich   88

[18000 rows x 2 columns]

In [32]:
# Select rows (by label)
df.loc[0]             # 1st row (by label)
df.loc[0:3]           # row0 to row3 - both inclusive in loc

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
0,2025-11-04 18:25:17.554219,US,New York,40.713,-74.006,50.295,108.938,27.998,6.539,52.568,1.096,108,18.504,70.168,3.725
1,2025-11-04 19:25:17.554219,US,New York,40.713,-74.006,32.083,63.043,36.120,4.021,43.536,1.075,90,5.838,80.088,8.969
2,2025-11-04 20:25:17.554219,US,New York,40.713,-74.006,42.250,82.553,26.935,9.538,23.320,0.977,84,31.833,62.783,9.650
3,2025-11-04 21:25:17.554219,US,New York,40.713,-74.006,30.403,79.951,63.536,7.609,31.369,0.230,158,23.140,89.153,8.956

In [36]:
# Select rows (by index)
df.iloc[0]            # 1st row 
df.iloc[4:7]          # 1st row

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
4,2025-11-04 22:25:17.554219,US,New York,40.713,-74.006,21.083,66.423,38.997,6.919,45.615,1.085,97,13.632,76.499,4.017
5,2025-11-04 23:25:17.554219,US,New York,40.713,-74.006,31.242,92.779,30.633,8.030,43.725,0.347,92,15.159,42.505,1.199
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542

In [34]:
# Select rows & columns
df.loc[0, "country"]  # 0th row & specific column
df.iloc[0, 2]         # 1th row & 3rd column (by position)

df.iloc[0, 1:5]
df.loc[0, ["country", "aqi"]]

df.loc[0:5, ["country", "city", "latitude"]]   # end is inclusive
df.iloc[0:5, 1:3]                              # end is exclusive

  country      city
0      US  New York
1      US  New York
2      US  New York
3      US  New York
4      US  New York

In [35]:
# Select single scalar value
df.at[0, "city"]
df.iat[0, 2]

'New York'

In [43]:
# Filtering Data
df[df["aqi"] > 100]
df[df["aqi"] > 100][["city", "aqi"]]

df[(df["aqi"] > 100) & (df["timestamp"] == "2025-11-04 18:25:17.554219")]
aqi_data = df[(df["aqi"] > 100) & (df["timestamp"] == "2025-11-04 18:25:17.554219")][["city", "aqi"]]

# Difference in loc & iloc - both give same value
aqi_data.loc[360] 
aqi_data.iloc[1]

city    Los Angeles
aqi             112
Name: 360, dtype: object

In [46]:
# Use .copy() to avoid confusion
countries = df[["country", "aqi"]].copy()
countries.loc[0:4, "country"] = "India"

print(countries)

      country  aqi
0       India  108
1       India   90
2       India   84
3       India  158
4       India   97
...       ...  ...
17995      CH  103
17996      CH  105
17997      CH  122
17998      CH   95
17999      CH   88

[18000 rows x 2 columns]

In [51]:
# Cleaning Data
df = pd.read_csv("raw_data.csv") 
# Handle Missing values
df.isnull()            # True for null values (NaN)
df.isnull().sum()      # counts missing vals per column

id         0
name       1
age        3
country    1
gender     1
income     1
dtype: int64

In [55]:


df.dropna()            # drops rows with missing values
df.dropna(axis = 1)    # drops cols with missing values

df.fillna(0)           # fills NaN with value
df["age"] = df["age"].fillna(df["age"].mean())           # fills column with mean

df.ffill()             # forward fill
df.bfill()             # backward fill

    id          name    age country   gender   income
0    1      John Doe  29.00     USA     Male  55000.0
1    1      John Doe  29.00     USA     Male  55000.0
2    2    Jane Smith  32.75  Canada   Female  62000.0
3    3          Alex  32.75     USA  Unknown  47000.0
4    4  Maria Garcia  34.00   Spain   Female  51000.0
5    5        Li Wei  27.00   China     Male  51000.0
6    6    Ahmed Khan  45.00   India   Female  73000.0
7    7    Ahmed Khan  38.00     USA     Male  68000.0
8    8    Rachel Lee  29.00     USA   Female  62000.0
9    9   Carlos Ruiz  32.75  Mexico     Male  45000.0
10  10   Emily Davis  31.00     USA      NaN  58000.0

In [56]:
# Handle Duplicate values
df = pd.read_csv("raw_data.csv") 

df.duplicated()                      # True for duplicate rows
df.duplicated("country")             # True for duplicate rows in particular col
df.duplicated(["country", "gender"]) 

df.drop_duplicates()                 # drops duplicate rows

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [57]:
# Handle Data Types
df = pd.read_csv("raw_data.csv") 

df.dtypes                                     # dtype of each col
df2 = df.fillna(0).copy()
df2["income"] = df2["income"].astype(int)       # change dtype

# String type
df2["gender"].str.lower()                      # lower case
df2["gender"].str.upper()                      # upper case
df2["gender"].str.capitalize()                 # capitalize

df2["gender"].str.capitalize()                 # capitalize
df2["name"].str.split(" ")                     # splits into lists based on separator value 
type(df2["name"].str.split(" ")[0])            

df2["country"].str.contains("US")
df2["country"].str.contains("india", case=False)

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7       NaN
8     False
9     False
10    False
Name: country, dtype: object